### ISSUE TITLE
Create tag for new releases

### ISSUE THREAD

**Issue by anitacaron** [adeans/gallont#3]
The OBO Dashboard is still failing for the versioning principle because it's not resolving. https://dashboard.obofoundry.org/dashboard/gallont/dashboard.html

To fix this, you need to create a tag with every release. The tag should be `vYYYY-MM-DD`. The date should be the same as when the artefacts were generated. You can find how to create a release in GitHub [here](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release)

**Comment by adeans** [comment]
Hopefully this is fixed now. Thanks for letting me know!

**Comment by anitacaron** [comment]
The release creation is correct, thanks! We'll confirm it with the next OBO Dashboard release next month!
